version: '3'
services:
  liferay:
    image: liferay/portal:7.2.0-rc2
    restart: always
    ports:
      - "8383:8080"
      - "11311:11311"
    environment:
# use .env file? see https://docs.docker.com/compose/env-file/
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME: com.mysql.cj.jdbc.Driver
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL: "jdbc:mysql://db/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true"
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME: liferay
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD: liferaySuperSecretPassword
    depends_on:
      - db

# Uncomment next 2 lines for demo #2 (restrict locales to German and English)
#    environment:
#      LIFERAY_LOCALES_PERIOD_ENABLED: de_DE,en_US,hu_HU
# Uncomment next 2 lines for demo #3 (inject scripts, files, plugins on startup)
    volumes:
      - ./conf/liferay:/etc/liferay
#      - "D:\\repos\\liferay-docker-demo\\conf\\liferay:/etc/liferay/mount"
  db:
# NOTE: connector conf/liferay/files/tomcat/lib/ext/mysql-connector-java-8.0.16.jar
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
# Use root/exampleRootPassword as user/password credentials
      MYSQL_ROOT_PASSWORD: exampleRootPassword
      MYSQL_USER: liferay
      MYSQL_PASSWORD: liferaySuperSecretPassword
      MYSQL_DATABASE: lportal
    ports:
# for debugging:
      - "3306:3306"

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '8181:80'
      - '9443:443'
      - '9022:22'
    volumes:
      - './data/gitlab/config:/etc/gitlab'
      - './data/gitlab/logs:/var/log/gitlab'
      - './data/gitlab/data:/var/opt/gitlab'

  jenkins:
    image: 'jenkins/jenkins:lts'
    restart: always
    ports:
      - '8282:8080'
      - '50000:50000'
    volumes:
      - 'jenkins_home:/var/jenkins_home'

volumes:
  jenkins_home:
